### ISSUE TITLE
Add functionality for handling "unsafe" jobs

### ISSUE THREAD

**Issue by jeremyong** [erlware/erlcron#14]
## Feature proposal

Currently, erlcron supports the handling of arbitrary function calls to Erlang. It would be nice to provide a convenience layer for handling external scripts (via `os:cmd/1` for example).

Things to take care of:
- Actual script execution and API
- Storing the PID for cancellation purposes
- Providing a cancel function that terminates the stored PID and/or all child PIDs spawned
- Piping process output to a log somewhere so that erlcron can return the log after being given a jobref

I am uncertain of the following:
- OS compatibility (I use linux primarily with a bit of osx)
- Job ref syntax

This feature will have to make some assumptions about the external service being run. Thoughts?

**Comment by saleyn** [comment]
This can be accomplished by using [erlexec](https://github.com/saleyn/erlexec) dependency.
