### ISSUE TITLE
erlcron conflicts with the UNIX at command

### ISSUE THREAD

**Issue by timClicks** [erlware/erlcron#16]
In UNIX, the `at` command allows users to run a job once at a particular time. In `erlcron`, it schedules something to occur daily.

This behaviour is confusing. I recommending changing the `erlcron` function to `daily` and adding a shortcut for a single-shot job that is being called in the future that is called `at`.

**Comment by Santiniis** [comment]
Closing this as @saleyn addressed in his PR and fixed the issue
