### ISSUE TITLE
Scheduling a job in the past crashes erlcron

### ISSUE THREAD

**Issue by pmembrey** [erlware/erlcron#20]
Hi,

I've found that if you try and schedule a task to run with erlcron:once in the past, the application crashes. The supervisor is expecting to receive {ok,_} but it receives {error,_} which then crashes erlcron and brings down the whole application. Here's the code (ecrn_cron_sup.erl):

```
%% @doc
%%  Add a chron job to be supervised
-spec add_job/2 :: (erlcron:job_ref(), erlcron:job()) -> erlcron:job_ref().
add_job(JobRef, Task) ->
{ok, _} = supervisor:start_child(?SERVER, [JobRef, Task]),
JobRef.
```

This is an issue because say on start up I schedule a task to be run at midday. This runs and all goes well, but I restart the app for some reason at 12:30. When the application starts back up, it will crash because erlcron crashes due to the time being in the past. 

The canonical behaviour in Unix cron is to simply not run a task that is in the past. I believe that erlcron should probably mimic this behaviour too. If I schedule a task for 2 minutes in the past, it should simply not run.

At the least there should be some way of communicating that the task won't actually run rather than the application crashing.

That said I'm not sure what the desired behaviour really should be and so I'm open to any suggestions about how else I can handle the problem...

Thanks in advance!

**Comment by saleyn** [comment]
This has been fixed in the master branch when the cron engine was rewritten a while back.
