### ISSUE TITLE
Timeout with jobs monthly R16B02

### ISSUE THREAD

**Issue by stuartT4** [erlware/erlcron#24]
When ecrn_agent:init/1 is setting up a monthly job it crashes because the timeout is too long.

The timeout i calculated for example is 
4835019000

  You can simulate this error by using the following 

receive void -> void after 4835019000 -> time end.

*\* exception error: bad receive timeout value
     in function  prim_eval:'receive'/2

**Comment by Santiniis** [comment]
Closing this as we're dropping the support for older releases of OTP
