### ISSUE TITLE
Inaccurate calculation of monthly timeout/apply time.

### ISSUE THREAD

**Issue by stuartT4** [erlware/erlcron#25]
The calculation of the timeout is inaccurate when it comes to monthly and the time has already passed for today, For example today is the second I want to run a process on the 1st of next month, at 1 am, however it is already 1pm today.

If I do ecrn_agent:until_next_milliseconds(NewState, Job).  
{ok,2634180000}

That gives me ~=  30 day 11 hr. 43 min.

ecrn_agent:until_next_daytime_or_days_from_now(NewState ,  {1,5,0}, 30).
2547909

which when I convert that to milliseconds is ~=  29 day 11 hr. 45 min. 9 sec. Which seems to be correct according to my manual calculation.

 So I propose in ecrn_agent changing the following code.

case Today of
        DoM ->
            until_next_daytime_or_days_from_now(State, Period, Days);
        _ ->
            until_days_from_now(State, Period, Days)
    end

and replace with

until_next_daytime_or_days_from_now(State, Period, Days)

Making the complete function the following.

until_next_time(State, {{monthly, DoM, Period}, _What}) ->
    {{ThisYear, ThisMonth, Today}, _} = current_date(State),

```
Days = case calendar:date_to_gregorian_days(ThisYear, ThisMonth, DoM)  - calendar:date_to_gregorian_days(ThisYear, ThisMonth, Today) of
    Res when Res < 0 ->
            {NextYear, NextMonth} =
            case ThisMonth of
                12 ->
                    {ThisYear + 1, 1};
                _  ->
                    {ThisYear, ThisMonth + 1}
            end,
            D1 = calendar:date_to_gregorian_days(ThisYear, ThisMonth, Today),
            D2 = calendar:date_to_gregorian_days(NextYear, NextMonth, DoM),
            D2 - D1;
   Ds ->
       Ds
end,

until_next_daytime_or_days_from_now(State, Period, Days).
```

**Comment by GeraldXv** [comment]
critical bug, but no one maintain.
