### ISSUE TITLE
find a bug

### ISSUE THREAD

**Issue by lintingbin2009** [erlware/erlcron#31]
do_job_run(State, {_, Job})
  when is_record(State, state), is_function(Job) ->
    RunFun = fun() ->
                     Job(State#state.alarm_ref, current_date(State))
             end,
    proc_lib:spawn(RunFun);
do_job_run(State, {_, {M, F, A}})
  when is_record(State, state) ->
    proc_lib:spawn(M, F, A).

If Job is "fun() -> io:format("hello world!") end", the statment "Job(State#state.alarm_ref, current_date(State))" will has badarity error.

**Comment by ericbmerritt** [comment]
@lintingbin2009 thanks. I will take a look.

**Comment by lintingbin2009** [comment]
You not fix it.
do_job_run() function only support MFA function, but not support an anonymous function(like fun() -> io:format("hello world!") end).

**Comment by saleyn** [comment]
This is already fixed in the latest commits.
