### ISSUE TITLE
Succesive calls to erlcron:datetime() return the same date

### ISSUE THREAD

**Issue by juangamella** [erlware/erlcron#36]
Calls to erlcron:datetime() always return the same date/time, even though they are performed seconds apart.

``` shell
2> erlcron:datetime().
{{{2015,9,23},{12,30,3}},1443004203}
3> erlcron:datetime().
{{{2015,9,23},{12,30,3}},1443004203}
4> erlcron:datetime().
{{{2015,9,23},{12,30,3}},1443004203}
```

However, job execution seems to be working fine

**Comment by ericbmerritt** [comment]
Hmm, that is interesting. I will take a look.

**Comment by Santiniis** [comment]
Closing this as @saleyn addressed this in his PR and fixed the issue.
