### ISSUE TITLE
syntax error before: '/'

### ISSUE THREAD

**Issue by zpeters** [erlware/erlcron#42]
This might be something that i'm doing wrong but when i try to build erlcron using erlang.mk (adding it to my Makefiles DEPS line) i get the following error:

Happy to do more testing or send more info if it helps

make
 DEP    erlcron
 DEP    rebar_vsn_plugin
 DEPEND rebar_vsn_plugin.d
 ERLC   rebar_vsn_plugin.erl
 APP    rebar_vsn_plugin.app.src
sed "s/{{EXTRA_OPTS}}/ {d,namespaced_types},/" Emakefile.src > Emakefile
erl -noinput -eval 'up_to_date = make:all()' -s erlang halt
make[2]: Nothing to be done for `compile'.
make[2]: Nothing to be done for`compile'.
make[2]: Nothing to be done for `compile'.
make[2]: Nothing to be done for`compile'.
 DEPEND erlcron.d
 ERLC   ecrn_agent.erl ecrn_app.erl ecrn_control.erl ecrn_cron_sup.erl ecrn_reg.erl ecrn_sup.erl ecrn_test.erl ecrn_util.erl erlcron.erl
src/ecrn_agent.erl:48: syntax error before: '/'
src/ecrn_agent.erl:53: syntax error before: '/'
src/ecrn_agent.erl:57: syntax error before: '/'
src/ecrn_agent.erl:61: syntax error before: '/'
src/ecrn_agent.erl:65: syntax error before: '/'
src/ecrn_agent.erl:71: syntax error before: '/'
src/ecrn_agent.erl:167: syntax error before: '/'
src/ecrn_agent.erl:181: syntax error before: '/'
src/ecrn_agent.erl:203: syntax error before: '/'
src/ecrn_agent.erl:247: syntax error before: '/'
src/ecrn_agent.erl:259: syntax error before: '/'
src/ecrn_agent.erl:265: syntax error before: '/'
src/ecrn_agent.erl:270: syntax error before: '/'
src/ecrn_agent.erl:283: syntax error before: '/'
src/ecrn_agent.erl:302: syntax error before: '/'
src/ecrn_agent.erl:319: syntax error before: '/'
src/ecrn_agent.erl:329: syntax error before: '/'
src/ecrn_agent.erl:347: syntax error before: '/'
src/ecrn_agent.erl:353: syntax error before: '/'
src/ecrn_agent.erl:360: syntax error before: '/'
src/ecrn_agent.erl:40: Warning: type state() is unused
make[2]: **\* [ebin/erlcron.app] Error 1
make[1]: **\* [app] Error 2
make: **\* [deps] Error 2

**Comment by nestor5** [comment]
See issue #39 , I don't understand why the PR is still not merged

**Comment by ericbmerritt** [comment]
It's mostly a matter that none of us really use erlcron anymore and no one has stepped up to take over maintenance. If you are interested we can definitely use the help.

**Comment by getong** [comment]
@ericbmerritt What lib are you using for cron jobs? Just curious to know.

**Comment by ericbmerritt** [comment]
@getong I am not doing a lot of Erlang anymore. If I were, this is the one I would use. 

Though, I should say that we really do need to look for a maintainer.

**Comment by RandomSeeded** [comment]
@ericbmerritt looks like there's currently 3 PRs out to fix this, can any of them be merged?

https://github.com/erlware/erlcron/pull/40
https://github.com/erlware/erlcron/pull/43
https://github.com/erlware/erlcron/pull/41

Also let me know what you're looking for in a maintainer. I'd be happy to help with no-brainery stuff like this but am definitely not an erlang expert, would not feel comfortable judging larger changes to the codebase.

**Comment by RandomSeeded** [comment]
Sounds great; I'd be happy to help where I can.

https://github.com/erlware/erlcron/pull/40 in particular is the minimal necessary change.

**Comment by ericbmerritt** [comment]
You have an invite. Please be intentional about what you merge. At the very least ensure that things build and run. Thanks man.

**Comment by RandomSeeded** [comment]
ty, will verify correctness of patches and merge in within next day or two

**Comment by RandomSeeded** [comment]
Fixed in https://github.com/erlware/erlcron/pull/40, thanks @zpeters
