### ISSUE TITLE
Problems if the cron process crash or is canced.

### ISSUE THREAD

**Issue by yjcdll** [erlware/erlcron#47]
% Start the application.
1> application:start(erlcron).
ok

% Start a job and get its Pid through job_ref.
2> f(),Ref=erlcron:cron({{once,100},{io,format,["hungry"]}}),{ok,[Pid]}=ecrn_reg:get(Ref).
{ok,[<0.60.0>]}

%	Kill the Pid.
3> exit(pid(0,60,0),kill).
true

% Get the Pid.
4> ecrn_reg:get(Ref).
{ok,[<0.60.0>,<0.62.0>]}

%	Kill the Pid.
5> exit(pid(0,62,0),kill).
true

% Get the Pid.
6> ecrn_reg:get(Ref).
{ok,[<0.60.0>,<0.62.0>,<0.65.0>]}

% After 100 seconds, the shell will print hungry.
7> hungry

So here comes the problem, I wish to run a task after 100 seconds, but unfortunately, the cron process crashes after 50 seconds, and then restart. Finally, the task will be run after 150 seconds.

1> application:start(erlcron).
ok

2> f(),Ref=erlcron:cron({{once,100},{io,format,["hungry"]}}),{ok,[Pid]}=ecrn_reg:get(Ref).
{ok,[<0.60.0>]}

3> exit(pid(0,60,0),kill).
true

4> ecrn_reg:get(Ref).
{ok,[<0.60.0>,<0.62.0>]}

5> exit(pid(0,62,0),kill).
true

6> ecrn_reg:get(Ref).
{ok,[<0.60.0>,<0.62.0>,<0.65.0>]}

7> erlcron:cancel(Ref).

=ERROR REPORT==== 14-Jan-2018::18:20:18 ===
** Generic server ecrn_control terminating 
** Last message in was {cancel,#Ref<0.0.1.111>}
** When Server state == {state,{{2018,1,14},{18,18,46}},1515982726}
** Reason for termination == 
** {{case_clause,{ok,[<0.60.0>,<0.62.0>,<0.65.0>]}},
    [{ecrn_control,internal_cancel,1,
                   [{file,"src/ecrn_control.erl"},{line,111}]},
     {ecrn_control,handle_call,3,[{file,"src/ecrn_control.erl"},{line,68}]},
     {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
** exception exit: {{{case_clause,{ok,[<0.60.0>,<0.62.0>,<0.65.0>]}},
                     [{ecrn_control,internal_cancel,1,
                                    [{file,"src/ecrn_control.erl"},{line,111}]},
                      {ecrn_control,handle_call,3,
                                    [{file,"src/ecrn_control.erl"},{line,68}]},
                      {gen_server,try_handle_call,4,
                                  [{file,"gen_server.erl"},{line,629}]},
                      {gen_server,handle_msg,5,
                                  [{file,"gen_server.erl"},{line,661}]},
                      {proc_lib,init_p_do_apply,3,
                                [{file,"proc_lib.erl"},{line,240}]}]},
                    {gen_server,call,[ecrn_control,{cancel,#Ref<0.0.1.111>}]}}
     in function  gen_server:call/2 (gen_server.erl, line 204)
	 
	 
In this case, if I cancel this job, it will cause an exception, which I think should be fixed.

**Comment by RandomSeeded** [comment]
Hey mate, tbh this project is pretty much entirely unmaintained. I'm not original owner / maintainer but I do have push access, so if you write a PR for it I'll try to take a look. Do feel free to ping original maintainers if you want to try to get yourself access.

**Comment by Santiniis** [comment]
Bug fixed by PR by @saleyn. Closing the issue.
