### ISSUE TITLE
{tag, "master"} ?

### ISSUE THREAD

**Issue by tothlac** [erlware/erlcron#51]
That's in rebar.config

{deps, [{rebar_vsn_plugin, ".*",
         {git, "https://github.com/erlware/rebar_vsn_plugin.git",
          {tag, "master"}}}]}.

Can you fix it?

**Comment by tothlac** [comment]
I've created a pull request for this: https://github.com/erlware/erlcron/pull/53
Could you please merge it?

**Comment by vkatsuba** [comment]
I suppose this issue can be close. 
cc @Santiniis
