### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by tsloughter** [erlware/erlcron#54]
Sorry I didn't do this earlier, is anyone interesting in taking this project?

I do not use it and have never looked at it. I noticed it had recent issues/pull requests so took a look and seems there are people using it and possibly interested in taking ownership.

**Comment by Santiniis** [comment]
I'd be interested in taking ownership and maintaining the repository.

**Comment by tsloughter** [comment]
Ok @maximvl and @Santiniis are added as maintainers. One of us 3 still has to review any PR before it is able to be merged and the project will remain under erlware for the time being.

**Comment by saleyn** [comment]
@tsloughter, could you add me as a maintainer, since I see that there's been issues/PRs sitting for a while and I just submitted another one?

**Comment by tsloughter** [comment]
@saleyn sent. And @maximvl was removed.

**Comment by saleyn** [comment]
@tsloughter, could you approve my PR, since it does require a reviewer different from the submitter?
