### ISSUE TITLE
Push lib to hex.pm

### ISSUE THREAD

**Issue by vkatsuba** [erlware/erlcron#67]
Hi All,

Please push this lib to the hex.pm. Thanks!

Best Regards,
--V

**Comment by Santiniis** [comment]
Will do as soon as I have some time. Probably next week.

**Comment by vkatsuba** [comment]
I can do it and create a CI for automatically pushing to hex.pm. But will need add the key into `HEX_API_KEY`. But of course this is up to you.

**Comment by vkatsuba** [comment]
And.. I close this issue - because this is duplicate of https://github.com/erlware/erlcron/issues/49.
