### ISSUE TITLE
Application fails to start when jobs are defined in the config file

### ISSUE THREAD

**Issue by emtenet** [erlware/erlcron#71]
When `erlcron:cron/2` successfully starts a job, it returns a `job_ref()`:
https://github.com/erlware/erlcron/blob/00e9068803f8e11eaf1655bb370daddcc3310854/src/erlcron.erl#L131-L132

When starting jobs during application startup, it expects `erlcron:cron/2` to return `ok` for success:
https://github.com/erlware/erlcron/blob/00e9068803f8e11eaf1655bb370daddcc3310854/src/ecrn_app.erl#L60-L69

This missmatch in expectations causes the `erlcron` application startup to fail in the presense of jobs defined in the config file.

**Comment by saleyn** [comment]
This is fixed in PR #72
